name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci || npm i
        working-directory: .

      - name: Build
        run: npm run build
        working-directory: .

      - name: Package dist
        run: |
          tar -czf dist.tgz dist
        working-directory: .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: typescript-dist
          path: |
            dist.tgz
            dist/**
          if-no-files-found: error
