name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout commit from CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN || secrets.npm_token }}
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "Missing NPM token (NPM_TOKEN or npm_token)" >&2
            exit 1
          fi
          npm publish --access public

      # GitHub Release is created in auto-tag workflow after tag is pushed
